### ISSUE TITLE
Fetch cannot build

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#1085]
Something you did in the last 12h or so causes Fetch to fail building. The following is what I get back from the CSSWG API server:
```
Error running preprocessor, returned code: 1.
Traceback (most recent call last):
  File "/sites/api.csswg.org/bikeshed/bikeshed.py", line 5, in 
    bikeshed.main()
  File "/sites/api.csswg.org/bikeshed/bikeshed/cli.py", line 193, in main
    doc.preprocess()
  File "/sites/api.csswg.org/bikeshed/bikeshed/Spec.py", line 171, in preprocess
    processBiblioLinks(self)
  File "/sites/api.csswg.org/bikeshed/bikeshed/unsortedJunk.py", line 626, in processBiblioLinks
    ref = doc.refs.getBiblioRef(linkText, status=refStatus, generateFakeRef=okayToFail, silentAliases=okayToFail, el=el)
  File "/sites/api.csswg.org/bikeshed/bikeshed/refs/ReferenceManager.py", line 483, in getBiblioRef
    bib = self.getBiblioRef(candidate["aliasOf"], status=status, el=el, quiet=True)
  File "/sites/api.csswg.org/bikeshed/bikeshed/refs/ReferenceManager.py", line 480, in getBiblioRef
    bib = biblio.StringBiblioEntry(**candidate)
  File "", line 22, in __init__
  File "/sites/api.csswg.org/bikeshed/bikeshed/biblio.py", line 31, in __attrs_post_init__
    self.preferredURL = config.refStatus.snapshot
  File "/sites/api.csswg.org/bikeshed/bikeshed/attr/_make.py", line 240, in _frozen_setattrs
    raise FrozenInstanceError()
bikeshed.attr.exceptions.FrozenInstanceError
```

**Comment by foolip** [comment]
I have bisected and this specific exception started happening in commit 3172faa20ddceadd964dc78f3e7f9f938db928ec, the the preceding commit 5cca8a7df56a49b1d4633971bc2b5fb2dc1b99e3 had another issue. On of those two commits are the cause, though.

**Comment by foolip** [comment]
Tested with `make local` in https://github.com/whatwg/fetch/commit/c19355984d7a1c110574c46c20a41901df973e5a

**Comment by foolip** [comment]
The problem applies to the master branch of fetch as well, but not dom. It must have something to do with this bit in the source:
```
    "HTTP": {
        "aliasOf": "HTTP11"
    },
    "HTTP-SEMANTICS": {
        "aliasOf": "RFC7231"
    },
    "HTTP-COND": {
        "aliasOf": "RFC7232"
    },
    "HTTP-CACHING": {
        "aliasOf": "RFC7234"
    },
    "HTTP-RANGE": {
        "aliasOf": "RFC7233"
    },
    "HTTP-AUTH": {
        "aliasOf": "RFC7235"
    },
    "REFERRER": {
        "aliasOf": "referrer-policy"
    },
    "SW": {
        "aliasOf": "service-workers"
    },
    "UPGRADE": {
        "aliasOf": "upgrade-insecure-requests"
    },
    "HSTS": {
        "aliasOf": "rfc6797"
    },
    "WSP": {
        "aliasOf": "WEBSOCKETS-PROTOCOL"
    },
```

**Comment by foolip** [comment]
@tabatkins, is there an open issue for regression testing using all known existing specs using Bikeshed? If the main problem is getting and keep a list of repos up-to-date, that's something I think might naturally fall out of other things I'd like to do, so I'm interested to help.

**Comment by tabatkins** [comment]
Fixed, sorry. Was testing against DOM, but it doesn't exercise this particular path, and none of my automatic tests were using a string-based biblio entry either; I'll fix that.

@foolip No open issue yet; I'll open one.
