### ISSUE TITLE
bikeshed fails to build the latest DOM spec

### ISSUE THREAD

**Issue by TakayoshiKochi** [tabatkins/bikeshed#1092]
After revision 7662ed324a33038d0ccf9ddb6e473f076a7a5513, making dom spec
started to spew error in Python.

```
bikeshed spec dom.bs dom.html --md-Text-Macro="SNAPSHOT-LINK LOCAL COPY"
Traceback (most recent call last):
  File "/usr/local/bin/bikeshed", line 11, in <module>
    load_entry_point('Bikeshed', 'console_scripts', 'bikeshed')()
  File "/usr/local/google/home/kochi/gh/bikeshed/bikeshed/cli.py", line 200, in main
    doc.preprocess()
  File "/usr/local/google/home/kochi/gh/bikeshed/bikeshed/Spec.py", line 109, in preprocess
    self.mdDefaults = metadata.fromJson(data=config.retrieveBoilerplateFile(self, 'defaults', error=True))
  File "/usr/local/google/home/kochi/gh/bikeshed/bikeshed/metadata.py", line 766, in fromJson
    md.addData(key, val)
  File "/usr/local/google/home/kochi/gh/bikeshed/bikeshed/metadata.py", line 124, in addData
    val = md.parse(key=key, val=val, lineNum=lineNum)
  File "/usr/local/google/home/kochi/gh/bikeshed/bikeshed/metadata.py", line 474, in parseComplainAbout
    parseBoolishList(key, val.lower(), default=False, validLabels=validLabels, lineNum=lineNum)
  File "/usr/local/google/home/kochi/gh/bikeshed/bikeshed/metadata.py", line 492, in parseBoolishList
    name,_, boolstring = v.split().rpartition(" ")
AttributeError: 'list' object has no attribute 'rpartition'
make: *** [local] Error 1
```

**Comment by tabatkins** [comment]
This was fixed yesterday, please update Bikeshed. ^_^

(Run `git pull --rebase` inside the Bikeshed source folder.)
