### ISSUE TITLE
"All strings must be XML compatible" error could be more helpful

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#1099]
With a bad character, I get:

```
FATAL ERROR: Something went wrong while watching the file:
All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```

It would help to tell me what character to look for or what text surrounds it.

**Comment by tabatkins** [comment]
Huh, that error is percolating up from some library. Can you provide me with an example file that does it?  Or run bikeshed normally and give me the stack trace, at least.

**Comment by tabatkins** [comment]
(And yes, "you got a bad character somewhere in here, lol fuck you hope you choke while looking for it" errors infuriate the hell out of me too.)

**Comment by jyasskin** [comment]
Ok, reduced test case:
```bikeshed
<pre class='metadata'>
Title: Your Spec Title
Shortname: your-spec
Level: 1
Status: ED
Group: webappsec
URL: http://example.com/url-this-spec-will-live-at
Editor: Your Name, Your Company http://example.com/your-company, your-email@example.com, http://example.com/your-personal-website
Abstract: A short description of your spec, one or two sentences.
</pre>

Introduction {#intro}
=====================

<a idl for="Permissions" lt="query()">query(|permissionDesc|)</a>
```

Error:

```
WARNING: The following <var>s were only used once in the document:                                       
  'permissionDesc'
If these are not typos, please add an ignore='' attribute to the <var>.
Traceback (most recent call last):
  File "/usr/local/google/home/jyasskin/.local/bin/bikeshed", line 11, in <module>
    load_entry_point('Bikeshed', 'console_scripts', 'bikeshed')()
  File "/usr/local/google/home/jyasskin/src/bikeshed/bikeshed/cli.py", line 200, in main
    doc.preprocess()
  File "/usr/local/google/home/jyasskin/src/bikeshed/bikeshed/Spec.py", line 178, in preprocess
    processAutolinks(self)
  File "/usr/local/google/home/jyasskin/src/bikeshed/bikeshed/unsortedJunk.py", line 728, in processAutolinks
    el.set('href', ref.url)
  File "src/lxml/lxml.etree.pyx", line 824, in lxml.etree._Element.set (src/lxml/lxml.etree.c:51607)
  File "src/lxml/apihelpers.pxi", line 574, in lxml.etree._setAttributeValue (src/lxml/lxml.etree.c:23257)
  File "src/lxml/apihelpers.pxi", line 1443, in lxml.etree._utf8 (src/lxml/lxml.etree.c:31876)           
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters  
```

I have bikeshed data `2017-09-20 22:10:49.226405`.

**Comment by jyasskin** [comment]
And `ref.url` is `https://w3c.github.io/permissions/#dom-permissions-query①`, although I don't know what bytes it actually contains.

**Comment by tabatkins** [comment]
This is why the unicode sandwich is a good idea, kids.

Fixed now, but also please now fix Permissions to not have a fatal duplicate ID on one of its definitions. ^_^

**Comment by jyasskin** [comment]
Thanks and done.
