### ISSUE TITLE
NameError: global name 'filename' is not defined

### ISSUE THREAD

**Issue by andypaicu** [tabatkins/bikeshed#1110]
Bikeshed is throwing an error when trying to process the webappsec-csp spec.

Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.13/bin/bikeshed", line 11, in <module>
    load_entry_point('Bikeshed', 'console_scripts', 'bikeshed')()
  File "/home/travis/build/w3c/webappsec-csp/bikeshed/bikeshed/cli.py", line 201, in main
    doc.preprocess()
  File "/home/travis/build/w3c/webappsec-csp/bikeshed/bikeshed/Spec.py", line 165, in preprocess
    processBiblioLinks(self)
  File "/home/travis/build/w3c/webappsec-csp/bikeshed/bikeshed/unsortedJunk.py", line 629, in processBiblioLinks
    ref = doc.refs.getBiblioRef(linkText, status=refStatus, generateFakeRef=okayToFail, silentAliases=okayToFail, el=el)
  File "/home/travis/build/w3c/webappsec-csp/bikeshed/bikeshed/refs/ReferenceManager.py", line 447, in getBiblioRef
    with config.retrieveDataFile("biblio/biblio-{0}.data".format(group), quiet=True) as lines:
  File "/home/travis/build/w3c/webappsec-csp/bikeshed/bikeshed/config/retrieve.py", line 24, in retrieveDataFile
    die("Couldn't retrieve the file '{0}' from cache. Something's wrong, please report this.", filename)
NameError: global name 'filename' is not defined

This occurred on this PR https://github.com/w3c/webappsec-csp/pull/247 but I have tried it with the master branch file and it happens as well.

**Comment by tabatkins** [comment]
Should be good now, sorry about that. (But it sounds like you're about to actually hit the fatal error, so I'll get another bug report in a bit. ^_^)

**Comment by andypaicu** [comment]
Yes, raised a bug for the actual error now. Thank you for looking at these so quickly.
