### ISSUE TITLE
Building the WebIDL spec crashes Bikeshed

### ISSUE THREAD

**Issue by tobie** [tabatkins/bikeshed#1166]
Getting the following error when attempting to build https://raw.githubusercontent.com/tobie/webidl/ff6413e87ab499badc6f84d9eafb340fcb013383/index.bs.

Last successful build using the Web API was on Jan 11, 2018, at 9:21 PM GMT.

```
Traceback (most recent call last):
  File "/usr/local/bin/bikeshed", line 9, in <module>
    load_entry_point('Bikeshed==0.0.0', 'console_scripts', 'bikeshed')()
  File "/Users/tobie/Repos/bikeshed/bikeshed/cli.py", line 202, in main
    doc.preprocess()
  File "/Users/tobie/Repos/bikeshed/bikeshed/Spec.py", line 124, in preprocess
    self.lines = datablocks.transformDataBlocks(self, self.lines)
  File "/Users/tobie/Repos/bikeshed/bikeshed/datablocks.py", line 101, in transformDataBlocks
    firstLine=blockLines[0].text,
IndexError: list index out of range
make: *** [index.html] Error 1
```

**Comment by tabatkins** [comment]
Should be fixed in 4fa4278e - WebIDL doesn't crash now. There's still some fiddliness that I think I got wrong, tho - working on that now.
