### ISSUE TITLE
Adding <wpt-rest> element causes error in wptElement.by

### ISSUE THREAD

**Issue by foolip** [tabatkins/bikeshed#1265]
Next step after https://github.com/tabatkins/bikeshed/issues/1264 is to add in `<wpt-rest>`, which I did in commit https://github.com/whatwg/fullscreen/commit/6d441ce1de99ed0d11979a13eacf46cb958f1575. With that state of the fullscreen spec and bikeshed 5888e02cf0071ba98c44312075d6903689282c04, this error results from `make local`:
```
bikeshed spec fullscreen.bs fullscreen.html --md-Text-Macro="SNAPSHOT-LINK LOCAL COPY"
Traceback (most recent call last):
  File "/usr/local/google/home/foolip/.local/bin/bikeshed", line 11, in <module>
    load_entry_point('Bikeshed', 'console_scripts', 'bikeshed')()
  File "/usr/local/google/home/foolip/src/bikeshed/bikeshed/cli.py", line 203, in main
    doc.preprocess()
  File "/usr/local/google/home/foolip/src/bikeshed/bikeshed/Spec.py", line 102, in preprocess
    self.processDocument()
  File "/usr/local/google/home/foolip/src/bikeshed/bikeshed/Spec.py", line 187, in processDocument
    wpt.processWptElements(self)
  File "/usr/local/google/home/foolip/src/bikeshed/bikeshed/wpt/wptElement.py", line 37, in processWptElements
    localPrefix = el.get("pathprefix")
UnboundLocalError: local variable 'el' referenced before assignment
Makefile:5: recipe for target 'local' failed
make: *** [local] Error 1
```

**Comment by tabatkins** [comment]
Ugh, Python loop scoping strikes again! I tested `wpt-rest`, but if you have any `wpt` elements this bit of code doesn't trigger any errors. (It's accidentally referring to the last `wpt` element in the document instead, due to the way python scopes loop variables. If there arne't any, that variable never gets initialized to anything and errors out.)
