### ISSUE TITLE
Can't run bikeshed spec on windows

### ISSUE THREAD

**Issue by mkruisselbrink** [tabatkins/bikeshed#1358]
Running `bikeshed spec` on windows fails with: 
```
Traceback (most recent call last):
  File "C:\python_27_amd64\files\Scripts\bikeshed-script.py", line 11, in <module>
    load_entry_point('Bikeshed', 'console_scripts', 'bikeshed')()
  File "c:\src\bikeshed\bikeshed\cli.py", line 204, in main
    handleSpec(options, extras)
  File "c:\src\bikeshed\bikeshed\cli.py", line 240, in handleSpec
    doc.preprocess()
  File "c:\src\bikeshed\bikeshed\Spec.py", line 103, in preprocess
    self.processDocument()
  File "c:\src\bikeshed\bikeshed\Spec.py", line 161, in processDocument
    boilerplate.addBikeshedVersion(self)
  File "c:\src\bikeshed\bikeshed\boilerplate.py", line 20, in addBikeshedVersion
    bikeshedVersion = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=config.scriptPath()).rstrip()
  File "C:\python_27_amd64\files\lib\subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\python_27_amd64\files\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\python_27_amd64\files\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

This is because apparently on windows `subprocess.check_output` doesn't search PATH for the executable, so it will never be able to find and run git. Adding `shell=True` to the subprocess calls seems to be one way to work around this, but maybe there are better ways?

**Comment by tabatkins** [comment]
Hm! I'm fine with adding `shell=True`; it's safe to do so if you control the command. Thanks for the report, will fix in a sec.

**Comment by mkruisselbrink** [comment]
Oh, I should have been more explicit, the other subprocess.check_ouptut in the file (to get the git revision of the spec itself) is equally problematic (since you're only catching subprocess.CalledProcessError).

**Comment by tabatkins** [comment]
Ah, dang, sorry. Not being able to reproduce the bug myself makes this annoying. ^_^

Anyway, switched over to shell=True for both of those calls too, let me know if this fixes things?

**Comment by mkruisselbrink** [comment]
Thanks, things seem to be working great now!
