### ISSUE TITLE
Bikeshed failed to update

### ISSUE THREAD

**Issue by xfq** [tabatkins/bikeshed#1367]
`bikeshed update` emits the following output:

```
$ bikeshed update
Updating via manifest...
Traceback (most recent call last):
  File "/usr/local/bin/bikeshed", line 11, in <module>
    load_entry_point('Bikeshed', 'console_scripts', 'bikeshed')()
  File "/Users/xfq/git/bikeshed/bikeshed/cli.py", line 202, in main
    handleUpdate(options, extras)
  File "/Users/xfq/git/bikeshed/bikeshed/cli.py", line 230, in handleUpdate
    update.update(anchors=options.anchors, backrefs=options.backrefs, biblio=options.biblio, caniuse=options.caniuse, linkDefaults=options.linkDefaults, testSuites=options.testSuites, languages=options.languages, wpt=options.wpt, dryRun=config.dryRun, force=options.force)
  File "/Users/xfq/git/bikeshed/bikeshed/update/main.py", line 25, in update
    success = manifest.updateByManifest(path=path, dryRun=dryRun)
  File "/Users/xfq/git/bikeshed/bikeshed/update/manifest.py", line 120, in updateByManifest
    os.remove(localizePath(path, filePath))
OSError: [Errno 2] No such file or directory: '/Users/xfq/git/bikeshed/bikeshed/spec-data/headings/headings-css-timing-1.json'
```

Any clue how I should solve this issue?

**Comment by tabatkins** [comment]
I just pushed an update that checks the file exists before trying to delete it; re-up Bikeshed itself and see how it works.

(It's weird that this happens at all. It only deletes files that were in your old manifest but not in the new one; if it was in your old manifest, presumably you downloaded it. So why doesn't it exist?)

**Comment by xfq** [comment]
Although I'm not sure about the answer to your question, `bikeshed update` now works again after `git pull --rebase`. Thank you!

**Comment by tabatkins** [comment]
Sorry, the question was rhetorical and directed at myself. 😀
