### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'partition'

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#1412]
https://github.com/whatwg/encoding/pull/166/commits/b4dc096d48dc58f29d35730eaa0a249bd119f031 in https://github.com/whatwg/encoding/pull/166 resulted in https://travis-ci.org/whatwg/encoding/builds/467926809:
```
Error running preprocessor, returned code: 1.
Traceback (most recent call last):
  File "/sites/api.csswg.org/bikeshed/bikeshed.py", line 5, in 
    bikeshed.main()
  File "/sites/api.csswg.org/bikeshed/bikeshed/cli.py", line 204, in main
    handleSpec(options, extras)
  File "/sites/api.csswg.org/bikeshed/bikeshed/cli.py", line 240, in handleSpec
    doc.preprocess()
  File "/sites/api.csswg.org/bikeshed/bikeshed/Spec.py", line 102, in preprocess
    self.assembleDocument()
  File "/sites/api.csswg.org/bikeshed/bikeshed/Spec.py", line 117, in assembleDocument
    self.mdDefaults = metadata.fromJson(data=config.retrieveBoilerplateFile(self, 'defaults', error=True), source="defaults")
  File "/sites/api.csswg.org/bikeshed/bikeshed/config/retrieve.py", line 62, in retrieveBoilerplateFile
    megaGroup,_,status = doc.md.rawStatus.partition("/")
AttributeError: 'NoneType' object has no attribute 'partition'make: *** [deploy] Error 22
```
It seems to only happen when trying to build the living standard, the commit snapshot goes fine.

**Comment by tabatkins** [comment]
Fixed, thanks.
