### ISSUE TITLE
`bikeshed test` broken by bikeshed-data update

### ISSUE THREAD

**Issue by foolip** [tabatkins/bikeshed#1517]
`bikeshed update` + `bikeshed test --rebase` at commit f7860c06eaec18afc415bf3f4a7b90aee58ca680 fails like this:
```
194/404: Rebasing github/w3c/csswg-drafts/css-2015/Overview.bs
Traceback (most recent call last):
  File "/usr/local/google/home/foolip/.local/bin/bikeshed", line 11, in <module>
    load_entry_point('Bikeshed', 'console_scripts', 'bikeshed')()
  File "/usr/local/google/home/foolip/src/bikeshed/bikeshed/cli.py", line 221, in main
    handleTest(options, extras)
  File "/usr/local/google/home/foolip/src/bikeshed/bikeshed/cli.py", line 369, in handleTest
    test.rebase(Spec, options.testFiles, md=md)
  File "/usr/local/google/home/foolip/src/bikeshed/bikeshed/test.py", line 125, in rebase
    doc.preprocess()
  File "/usr/local/google/home/foolip/src/bikeshed/bikeshed/Spec.py", line 103, in preprocess
    self.processDocument()
  File "/usr/local/google/home/foolip/src/bikeshed/bikeshed/Spec.py", line 202, in processDocument
    boilerplate.addExplicitIndexes(self)
  File "/usr/local/google/home/foolip/src/bikeshed/bikeshed/boilerplate.py", line 317, in addExplicitIndexes
    for ref in doc.refs.queryAllRefs(dedupURLs=False, latestOnly=False, ignoreObsoletes=False):
  File "/usr/local/google/home/foolip/src/bikeshed/bikeshed/refs/ReferenceManager.py", line 245, in queryAllRefs
    r3,_ = self.foreignRefs.queryRefs(**kwargs)
  File "/usr/local/google/home/foolip/src/bikeshed/bikeshed/refs/RefSource.py", line 85, in queryRefs
    results,error = self._queryRefs(exact=True, **kwargs)
  File "/usr/local/google/home/foolip/src/bikeshed/bikeshed/refs/RefSource.py", line 127, in _queryRefs
    refs = list(allRefsIterator())
  File "/usr/local/google/home/foolip/src/bikeshed/bikeshed/refs/RefSource.py", line 96, in allRefsIterator
    for key, group in self.fetchAllRefs():
  File "/usr/local/google/home/foolip/src/bikeshed/bikeshed/refs/RefSource.py", line 75, in fetchAllRefs
    with self.dataFile.fetch("anchors", file) as fh:
  File "/usr/local/google/home/foolip/src/bikeshed/bikeshed/config/retrieve.py", line 35, in fetch
    return self._fail(location, str, okayToFail)
  File "/usr/local/google/home/foolip/src/bikeshed/bikeshed/config/retrieve.py", line 49, in _fail
    raise IOError("Couldn't find file '{0}'".format(location))
IOError: Couldn't find file '/usr/local/google/home/foolip/src/bikeshed/bikeshed/spec-data/readonly/anchors/anchors-xp.data'
```

anchors-xp.data indeed isn't there in the bikeshed repo.

I think the reason it's being searched for is because it was added in the bikeshed-data repo yesterday: https://github.com/tabatkins/bikeshed-data/commit/3f3083bb8f4085a8c16f4f3e3522d988caaa1daf

An automatic update to bikeshed-data should presumably not have the ability to break the bikeshed repo.

This has broken updates by https://github.com/foolip/bikeshed-tests.

**Comment by foolip** [comment]
Full list of specs which are broken like this:
- github/w3c/csswg-drafts/css-2015/Overview.bs
- github/w3c/csswg-drafts/css-2017/Overview.bs
- github/w3c/csswg-drafts/css-2018/Overview.bs
- github/w3c/csswg-drafts/css-env-1/Overview.bs
- github/w3c/csswg-drafts/indexes/Overview.bs

**Comment by foolip** [comment]
Actually just `bikeshed test` is also broken, not just rebasing.
