### ISSUE TITLE
(python3) `bikeshed issues-list` without argument fails

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#1624]
Since the switch to python 3, `bikeshed issues-list` fails when it is invoked without argument:
```
$ bikeshed issues-list
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin/bikeshed", line 11, in <module>
    load_entry_point('bikeshed', 'console_scripts', 'bikeshed')()
  File "/Users/florian/src/bikeshed/bikeshed/cli.py", line 223, in main
    handleIssuesList(options, extras)
  File "/Users/florian/src/bikeshed/bikeshed/cli.py", line 355, in handleIssuesList
    issuelist.printIssueList(options.infile, options.outfile)
  File "/Users/florian/src/bikeshed/bikeshed/issuelist.py", line 32, in printIssueList
    infilename = filenames[0][1]
IndexError: list index out of range
```
This does not happen when it is invoked with an explicit filename argument `bikeshed issues-list my-issues.txt`.

**Comment by tabatkins** [comment]
Release 1.2.1 contains the fix, too.

**Comment by frivoal** [comment]
Had to re-run `pip install -e .`, as this requires some new dependencies, but after that, but bug is indeed solved.
