### ISSUE TITLE
AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by TimothyGu** [tabatkins/bikeshed#1639]
On Python 3.8, running `bikeshed update` results in:

```
$ python3 -VV
Python 3.8.2 (default, Feb 26 2020, 22:21:03) 
[GCC 9.2.1 20200130]

$ bikeshed update
Updating via manifest...
Traceback (most recent call last):
  File "/home/timothy-gu/.local/bin/bikeshed", line 8, in <module>
    sys.exit(main())
  File "/home/timothy-gu/.local/lib/python3.8/site-packages/bikeshed/cli.py", line 210, in main
    handleUpdate(options, extras)
  File "/home/timothy-gu/.local/lib/python3.8/site-packages/bikeshed/cli.py", line 238, in handleUpdate
    update.update(anchors=options.anchors, backrefs=options.backrefs, biblio=options.biblio, caniuse=options.caniuse, mdn=options.mdn, linkDefaults=options.linkDefaults, testSuites=options.testSuites, languages=options.languages, wpt=options.wpt, dryRun=constants.dryRun, force=options.force)
  File "/home/timothy-gu/.local/lib/python3.8/site-packages/bikeshed/update/main.py", line 26, in update
    success = manifest.updateByManifest(path=path, dryRun=dryRun)
  File "/home/timothy-gu/.local/lib/python3.8/site-packages/bikeshed/update/manifest.py", line 132, in updateByManifest
    lastMsgTime = time.clock()
AttributeError: module 'time' has no attribute 'clock'
```

The function seems to have been [removed](https://docs.python.org/3.7/library/time.html#time.clock) in Python 3.8.

**Comment by tabatkins** [comment]
Interesting, thanks for the report. I'll fix on Monday.

**Comment by TimothyGu** [comment]
Fixing this in https://github.com/tabatkins/bikeshed/pull/1640.
