### ISSUE TITLE
Automatic <div algorithm> name deduction does not handle for=""

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#1645]
The case is something like this:

```html

<div algorithm>
 The <dfn id="byob-reader-cancel" method for="ReadableStreamBYOBReader">cancel(|reason|)</dfn>
 method steps are:

 1. If [=this=].\[[ownerReadableStream]] is undefined, return [=a promise rejected with=] a
    {{TypeError}} exception.
 1. Return ! [$ReadableStreamReaderGenericCancel$]([=this=], |reason|).
</div>

<div algorithm>
 The <dfn id="default-reader-cancel" method for="ReadableStreamDefaultReader">cancel(|reason|)</dfn>
 method steps are:

 1. If [=this=].\[[ownerReadableStream]] is undefined, return [=a promise rejected with=] a
    {{TypeError}} exception.
 1. Return ! [$ReadableStreamReaderGenericCancel$]([=this=], |reason|).
</div>
```

This tells me "Multiple declarations of the 'cancel(reason)' algorithm".

I can fix this by adding `="ReadableStreamBYOBReader cancel"` and `="ReadableStreamDefaultReader cancel"`, but it would be better if I didn't have to.

**Comment by tabatkins** [comment]
Ah yeah, that's an oversight. Fixed, thanks!

**Comment by domenic** [comment]
I tried to use this and got the following error:

```
Traceback (most recent call last):
  File "C:\Users\Domenic\AppData\Local\Programs\Python\Python38-32\Scripts\bikeshed-script.py", line 11, in <module>
    load_entry_point('bikeshed', 'console_scripts', 'bikeshed')()
  File "c:\users\domenic\dropbox\github\tabatkins\bikeshed\bikeshed\cli.py", line 212, in main
    handleSpec(options, extras)
  File "c:\users\domenic\dropbox\github\tabatkins\bikeshed\bikeshed\cli.py", line 248, in handleSpec
    doc.preprocess()
  File "c:\users\domenic\dropbox\github\tabatkins\bikeshed\bikeshed\Spec.py", line 107, in preprocess
    self.processDocument()
  File "c:\users\domenic\dropbox\github\tabatkins\bikeshed\bikeshed\Spec.py", line 185, in processDocument
    addImplicitAlgorithms(self)
  File "c:\users\domenic\dropbox\github\tabatkins\bikeshed\bikeshed\unsortedJunk.py", line 185, in addImplicitAlgorithms
    el.set("data-algorithm-for", dfnFor)
  File "src\lxml\etree.pyx", line 816, in lxml.etree._Element.set
  File "src\lxml\apihelpers.pxi", line 593, in lxml.etree._setAttributeValue
  File "src\lxml\apihelpers.pxi", line 1538, in lxml.etree._utf8
TypeError: Argument must be bytes or unicode, got 'NoneType'
```

(Actually, I get that error either with the fixed example too, now :(.)

**Comment by tabatkins** [comment]
Yup, just got the broken build notification and cut the bugfix release, sorry about that.

**Comment by domenic** [comment]
Works beautifully; thanks!
