### ISSUE TITLE
installation instructions fail on Mac because Pillow has unsatisfied dependency on jpeg

### ISSUE THREAD

**Issue by dbaron** [tabatkins/bikeshed#2153]
Following the [installation instructions](https://tabatkins.github.io/bikeshed/#install-final) (either of the released bikeshed or for development, though with `--user`) doesn't work on my relatively modern Mac, because when it tries to build Pillow, it fails with the error:

```
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
```

Those instructions say that I should install brew in order to install libjpeg... though it's not clear if that's actually the recommended path.

**Comment by tabatkins** [comment]
Unfortunately, I do not have access to a Mac to test these on, and rely on the community to fix any problems with the Mac install instructions. :( If you figure out a good way around this, please let me know.

**Comment by tabatkins** [comment]
Did this work, @dbaron?

**Comment by RobinMorisset** [comment]
I hit the same issue as @dbaron. After running `brew install libjpeg` and trying `pip3 install bikeshed && bikeshed update` again, I now have the following error:
```
Successfully installed Pillow-8.1.1 aiofiles-0.6.0 aiohttp-3.7.4 bikeshed-3.2.0 cssselect-1.1.0 isodate-0.6.0 json-home-client-1.1.1 lxml-4.6.3
Traceback (most recent call last):
  File "/Users/rmorisset/Library/Python/3.8/bin/bikeshed", line 5, in <module>
    from bikeshed import main
  File "/Users/rmorisset/Library/Python/3.8/lib/python/site-packages/bikeshed/__init__.py", line 65, in <module>
    from .Spec import Spec  # noqa: E402
  File "/Users/rmorisset/Library/Python/3.8/lib/python/site-packages/bikeshed/Spec.py", line 7, in <module>
    from . import (
  File "/Users/rmorisset/Library/Python/3.8/lib/python/site-packages/bikeshed/idl.py", line 8, in <module>
    from .unsortedJunk import classifyDfns
  File "/Users/rmorisset/Library/Python/3.8/lib/python/site-packages/bikeshed/unsortedJunk.py", line 6, in <module>
    from PIL import Image
  File "/Users/rmorisset/Library/Python/3.8/lib/python/site-packages/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/rmorisset/Library/Python/3.8/lib/python/site-packages/PIL/_imaging.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_jpeg_CreateCompress'
```

Following your suggestion, I tried updating pip with `python3 -m pip install --upgrade pip`, and got:
```
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.python.org/simple, https://pypi.apple.com/simple
Requirement already satisfied: pip in ./Library/Python/3.8/lib/python/site-packages (21.3.1)
```

Finally I tried `python3 -m pip install --upgrade Pillow`, and got
```
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.python.org/simple, https://pypi.apple.com/simple
Requirement already satisfied: Pillow in ./Library/Python/3.8/lib/python/site-packages (8.1.1)
Collecting Pillow
  Downloading https://pypi.apple.com/packages/packages/af/62/fc6e2c7ce2357d7c81866599ff5eae3cbae910880030d27233e2a9e2c4fb/Pillow-8.4.0-cp38-cp38-macosx_11_0_arm64.whl (2.8 MB)
     |████████████████████████████████| 2.8 MB 23.6 MB/s            
Installing collected packages: Pillow
  Attempting uninstall: Pillow
    Found existing installation: Pillow 8.1.1
    Uninstalling Pillow-8.1.1:
      Successfully uninstalled Pillow-8.1.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bikeshed 3.2.0 requires Pillow==8.1.1, but you have pillow 8.4.0 which is incompatible.
Successfully installed Pillow-8.4.0
```

**Comment by RobinMorisset** [comment]
I found a solution!

Running `python3 -m pip install bikeshed` (instead of `pip3 install bikeshed`), and then doing `python3 -m bikeshed ...` (instead of `bikeshed ...`) fixed the problem!

It seems like I have two different versions of python:
```
rmorisset@Robins-MacBook-Pro wgsl % which python3
/opt/homebrew/bin/python3
rmorisset@Robins-MacBook-Pro wgsl % which pip3
/Users/rmorisset/Library/Python/3.8/bin/pip3
```
And this was the root cause.

@dbaron can you try whether this also fixes the problem for you?

**Comment by dbaron** [comment]
No, it doesn't.  Both my `python3` and `pip3` are in `/usr/bin`.

**Comment by dbaron** [comment]
Upgrading pip got me through the pillow error to a later error, though.

**Comment by tabatkins** [comment]
So does that mean I can close this issue?

**Comment by dbaron** [comment]
Perhaps this could be closed with the addition of a note to https://tabatkins.github.io/bikeshed/#install-final that you might need to update pip?
