### ISSUE TITLE
wptScript.js not being installed correctly?

### ISSUE THREAD

**Issue by MatsPalmgren** [tabatkins/bikeshed#2174]
I just updated bikeshed like so:

```
# pip3 install --upgrade bikeshed && bikeshed update
Collecting bikeshed
  Downloading https://files.pythonhosted.org/packages/38/1e/f0cb0355dd92ec70f79c83a46bbcdcf5df5b4b89aaa05e41ae99b01c044c/bikeshed-3.3.1-py3-none-any.whl (10.6MB)
    100% |████████████████████████████████| 10.6MB 201kB/s 
Collecting tenacity==7.0.0 (from bikeshed)
  Using cached https://files.pythonhosted.org/packages/41/ee/d6eddff86161c6a3a1753af4a66b06cbc508d3b77ca4698cd0374cd66531/tenacity-7.0.0-py2.py3-none-any.whl
Collecting json-home-client==1.1.1 (from bikeshed)
  Using cached https://files.pythonhosted.org/packages/fd/92/df18b7eee481d53f951adad8c308d680766e8636c0a1a06112f05fb574cf/json_home_client-1.1.1-py3-none-any.whl
Collecting Pillow==8.1.1 (from bikeshed)
  Using cached https://files.pythonhosted.org/packages/b1/f9/5173fdbba404815d5109067ecde640dab908f4cd22b2c9de7bbedee46d67/Pillow-8.1.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting lxml==4.6.3 (from bikeshed)
  Using cached https://files.pythonhosted.org/packages/cf/4d/6537313bf58fe22b508f08cf3eb86b29b6f9edf68e00454224539421073b/lxml-4.6.3-cp37-cp37m-manylinux1_x86_64.whl
Collecting requests==2.25.1 (from bikeshed)
  Using cached https://files.pythonhosted.org/packages/29/c1/24814557f1d22c56d50280771a17307e6bf87b70727d975fd6b2ce6b014a/requests-2.25.1-py2.py3-none-any.whl
Collecting isodate==0.6.0 (from bikeshed)
  Using cached https://files.pythonhosted.org/packages/9b/9f/b36f7774ff5ea8e428fdcfc4bb332c39ee5b9362ddd3d40d9516a55221b2/isodate-0.6.0-py2.py3-none-any.whl
Collecting aiofiles==0.6.0 (from bikeshed)
  Using cached https://files.pythonhosted.org/packages/ba/21/df5eae4b6db2eb00d58428dd7f793ecbf99942fcafcea141cbf108fa72f4/aiofiles-0.6.0-py3-none-any.whl
Collecting widlparser==1.0.12 (from bikeshed)
  Using cached https://files.pythonhosted.org/packages/49/2c/ce832b41c0c550b3eb7a997245f0d501e3a44c70d6345ec80eb2cffa4141/widlparser-1.0.12-py3-none-any.whl
Collecting pygments==2.8.1 (from bikeshed)
  Using cached https://files.pythonhosted.org/packages/3a/80/a52c0a7c5939737c6dca75a831e89658ecb6f590fb7752ac777d221937b9/Pygments-2.8.1-py3-none-any.whl
Collecting html5lib==1.1 (from bikeshed)
  Using cached https://files.pythonhosted.org/packages/6c/dd/a834df6482147d48e225a49515aabc28974ad5a4ca3215c18a882565b028/html5lib-1.1-py2.py3-none-any.whl
Collecting cssselect==1.1.0 (from bikeshed)
  Using cached https://files.pythonhosted.org/packages/3b/d4/3b5c17f00cce85b9a1e6f91096e1cc8e8ede2e1be8e96b87ce1ed09e92c5/cssselect-1.1.0-py2.py3-none-any.whl
Collecting aiohttp==3.7.4 (from bikeshed)
Collecting attrs==20.3.0 (from bikeshed)
  Using cached https://files.pythonhosted.org/packages/c3/aa/cb45262569fcc047bf070b5de61813724d6726db83259222cd7b4c79821a/attrs-20.3.0-py2.py3-none-any.whl
Collecting certifi==2020.12.5 (from bikeshed)
  Using cached https://files.pythonhosted.org/packages/5e/a0/5f06e1e1d463903cf0c0eebeb751791119ed7a4b3737fdc9a77f1cdfb51f/certifi-2020.12.5-py2.py3-none-any.whl
Collecting result==0.6.0 (from bikeshed)
  Using cached https://files.pythonhosted.org/packages/e7/13/36e150c977018ba19adadc59e331d653460bb7733d2f733093e6f30d60bc/result-0.6.0-py3-none-any.whl
Collecting six>=1.9.0 (from tenacity==7.0.0->bikeshed)
  Using cached https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
Collecting uri-template (from json-home-client==1.1.1->bikeshed)
  Using cached https://files.pythonhosted.org/packages/e5/b9/6cf086d8aeda6ba04abc46da724818d48578398578ec64aa39bb7bb05997/uri_template-1.1.0-py3-none-any.whl
Collecting chardet<5,>=3.0.2 (from requests==2.25.1->bikeshed)
  Using cached https://files.pythonhosted.org/packages/19/c7/fa589626997dd07bd87d9269342ccb74b1720384a4d739a1872bd84fbe68/chardet-4.0.0-py2.py3-none-any.whl
Collecting urllib3<1.27,>=1.21.1 (from requests==2.25.1->bikeshed)
  Using cached https://files.pythonhosted.org/packages/af/f4/524415c0744552cce7d8bf3669af78e8a069514405ea4fcbd0cc44733744/urllib3-1.26.7-py2.py3-none-any.whl
Collecting idna<3,>=2.5 (from requests==2.25.1->bikeshed)
  Using cached https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl
Collecting typing-extensions>=3.7.4.1 (from widlparser==1.0.12->bikeshed)
  Downloading https://files.pythonhosted.org/packages/17/61/32c3ab8951142e061587d957226b5683d1387fb22d95b4f69186d92616d1/typing_extensions-4.0.0-py3-none-any.whl
Collecting webencodings (from html5lib==1.1->bikeshed)
  Using cached https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl
Collecting async-timeout<4.0,>=3.0 (from aiohttp==3.7.4->bikeshed)
  Using cached https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl
Collecting multidict<7.0,>=4.5 (from aiohttp==3.7.4->bikeshed)
  Using cached https://files.pythonhosted.org/packages/59/72/fb72624cd55492543f88ae492e5bc4dac7d6d55fde1bd4a03662b82dadf4/multidict-5.2.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
Collecting yarl<2.0,>=1.0 (from aiohttp==3.7.4->bikeshed)
  Downloading https://files.pythonhosted.org/packages/80/7f/af3ecdf87e8e41da7b133f1d61f82745f8c862bdade3b56addee3ad23956/yarl-1.7.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (271kB)
    100% |████████████████████████████████| 276kB 4.5MB/s 
Installing collected packages: six, tenacity, uri-template, json-home-client, Pillow, lxml, chardet, urllib3, certifi, idna, requests, isodate, aiofiles, typing-extensions, widlparser, pygments, webencodings, html5lib, cssselect, async-timeout, attrs, multidict, yarl, aiohttp, result, bikeshed
Successfully installed Pillow-8.1.1 aiofiles-0.6.0 aiohttp-3.7.4 async-timeout-3.0.1 attrs-21.2.0 bikeshed-3.3.1 certifi-2020.12.5 chardet-4.0.0 cssselect-1.1.0 html5lib-1.1 idna-2.10 isodate-0.6.0 json-home-client-1.1.1 lxml-4.6.3 multidict-5.2.0 pygments-2.8.1 requests-2.25.1 result-0.6.0 six-1.16.0 tenacity-7.0.0 typing-extensions-4.0.0 uri-template-1.1.0 urllib3-1.26.7 webencodings-0.5.1 widlparser-1.0.12 yarl-1.7.2
Updating via manifest...
Gathering local manifest data...
Fetching remote manifest data...
Deleted 1 old data file.
Updating 963 files...
Updated 642/963...
Done!
```

Then ran this command:

```
# bikeshed -f spec layout/docs/css-gap-decorations/Overview.bs
Traceback (most recent call last):
  File "/home/mats/.local/bin/bikeshed", line 11, in <module>
    sys.exit(main())
  File "/home/mats/.local/lib/python3.7/site-packages/bikeshed/cli.py", line 413, in main
    handleSpec(options, extras)
  File "/home/mats/.local/lib/python3.7/site-packages/bikeshed/cli.py", line 468, in handleSpec
    doc.preprocess()
  File "/home/mats/.local/lib/python3.7/site-packages/bikeshed/Spec.py", line 135, in preprocess
    self.processDocument()
  File "/home/mats/.local/lib/python3.7/site-packages/bikeshed/Spec.py", line 210, in processDocument
    wpt.processWptElements(self)
  File "/home/mats/.local/lib/python3.7/site-packages/bikeshed/wpt/wptElement.py", line 96, in processWptElements
    doc.extraScripts["script-wpt"] = getWptScript(pathPrefix)
  File "/home/mats/.local/lib/python3.7/site-packages/bikeshed/wpt/wptElement.py", line 447, in getWptScript
    with open(config.scriptPath("wpt", "wptScript.js"), "r", encoding="utf-8") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mats/.local/lib/python3.7/site-packages/bikeshed/wpt/wptScript.js'
```

**Comment by MatsPalmgren** [comment]
Fwiw, bikeshed works after I manually downloaded and installed https://raw.githubusercontent.com/tabatkins/bikeshed/main/bikeshed/wpt/wptScript.js to the given path.

**Comment by tabatkins** [comment]
Right, somebody pointed this out on Monday but I didn't quite get around to cutting a new release, and then BlinkOn distracted me. Sorry, fix pushed now. ^_^
