### ISSUE TITLE
Fatal error `name 'findAll' is not defined`

### ISSUE THREAD

**Issue by svgeesus** [tabatkins/bikeshed#2263]
Bikeshed (latest GitHub version) fails on CSS Color 4 if Prepare for TR: yes (it is fine with no):
```
$ bikeshed spec
Traceback (most recent call last):
  File "C:\Python38\Scripts\bikeshed-script.py", line 33, in <module>
    sys.exit(load_entry_point('bikeshed', 'console_scripts', 'bikeshed')())
  File "c:\users\chris\documents\github\bikeshed\bikeshed\cli.py", line 412, in main
    handleSpec(options, extras)
  File "c:\users\chris\documents\github\bikeshed\bikeshed\cli.py", line 467, in handleSpec
    doc.preprocess()
  File "c:\users\chris\documents\github\bikeshed\bikeshed\Spec.py", line 137, in preprocess
    self.processDocument()
  File "c:\users\chris\documents\github\bikeshed\bikeshed\Spec.py", line 299, in processDocument
    extensions.BSPrepTR(self)  # pylint: disable=no-member
  File "<string>", line 2, in BSPrepTR
NameError: name 'findAll' is not defined
```

**Comment by tabatkins** [comment]
So I'm trying to figure out just how you're even triggering that code.  The default-shipped version of the csswg boilerplates <https://github.com/tabatkins/bikeshed/blob/main/bikeshed/spec-data/readonly/boilerplate/csswg/bs-extensions.include> properly calls it from the `h` module, which I know works; the current version of the boilerplates <https://github.com/tabatkins/bikeshed-boilerplate/tree/main/boilerplate/csswg> doesn't have the bs-extensions file at all (it's no longer necessary).

I suspect you haven't run `bikeshed update` in a while, so you're looking at an old version of the boilerplate file?

**Comment by svgeesus** [comment]
> I suspect you haven't run bikeshed update in a while, so you're looking at an old version of the boilerplate file?

Yesterday, and again just now.

```
Chris@Nomad MINGW64 ~/Documents/GitHub/bikeshed (main)
$ python -m pip install --upgrade pip
Requirement already satisfied: pip in c:\python38\lib\site-packages (22.0.3)
Collecting pip
  Downloading pip-22.0.4-py3-none-any.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 2.9 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.3
    Uninstalling pip-22.0.3:
      Successfully uninstalled pip-22.0.3
Successfully installed pip-22.0.4

Chris@Nomad MINGW64 ~/Documents/GitHub/bikeshed (main)
$ pip3 install -e .
Obtaining file:///C:/Users/Chris/Documents/GitHub/bikeshed
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: html5lib==1.1 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (1.1)
Requirement already satisfied: tenacity==8.0.1 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (8.0.1)
Requirement already satisfied: isodate==0.6.1 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (0.6.1)
Requirement already satisfied: widlparser==1.0.12 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (1.0.12)
Requirement already satisfied: certifi==2021.10.8 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (2021.10.8)
Requirement already satisfied: async-timeout==4.0.2 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (4.0.2)
Requirement already satisfied: charset-normalizer==2.0.12 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (2.0.12)
Requirement already satisfied: lxml==4.8.0 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (4.8.0)
Requirement already satisfied: yarl==1.7.2 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (1.7.2)
Requirement already satisfied: json-home-client==1.1.1 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (1.1.1)
Requirement already satisfied: webencodings==0.5.1 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (0.5.1)
Requirement already satisfied: pygments==2.11.2 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (2.11.2)
Requirement already satisfied: pillow==9.0.1 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (9.0.1)
Requirement already satisfied: requests==2.27.1 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (2.27.1)
Requirement already satisfied: aiosignal==1.2.0 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (1.2.0)
Requirement already satisfied: frozenlist==1.3.0 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (1.3.0)
Requirement already satisfied: aiofiles==0.8.0 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (0.8.0)
Requirement already satisfied: attrs==21.4.0 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (21.4.0)
Requirement already satisfied: cssselect==1.1.0 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (1.1.0)
Requirement already satisfied: aiohttp==3.8.1 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (3.8.1)
Requirement already satisfied: six==1.16.0 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (1.16.0)
Requirement already satisfied: result==0.7.0 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (0.7.0)
Requirement already satisfied: uri-template==1.1.0 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (1.1.0)
Requirement already satisfied: multidict==6.0.2 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (6.0.2)
Requirement already satisfied: urllib3==1.26.8 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (1.26.8)
Requirement already satisfied: idna==3.3 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (3.3)
Requirement already satisfied: typing-extensions==4.1.1 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (4.1.1)
Installing collected packages: bikeshed
  Attempting uninstall: bikeshed
    Found existing installation: bikeshed 3.4.3
    Uninstalling bikeshed-3.4.3:
      Successfully uninstalled bikeshed-3.4.3
  Running setup.py develop for bikeshed
Successfully installed bikeshed-3.4.3

Chris@Nomad MINGW64 ~/Documents/GitHub/bikeshed (main)
$ bikeshed update
Updating via manifest...
Gathering local manifest data...
Fetching remote manifest data...
The local manifest is borked or missing; re-downloading everything...
Updating 2064 files...
Updated 911/2064...
Done!


Chris@Nomad MINGW64 ~/Documents/GitHub/bikeshed (main)
$ popd
~/Documents/GitHub/csswg-drafts/css-color-4

Chris@Nomad MINGW64 ~/Documents/GitHub/csswg-drafts/css-color-4 (main)
$ bikeshed spec
Traceback (most recent call last):
  File "C:\Python38\Scripts\bikeshed-script.py", line 33, in <module>
    sys.exit(load_entry_point('bikeshed', 'console_scripts', 'bikeshed')())
  File "c:\users\chris\documents\github\bikeshed\bikeshed\cli.py", line 412, in main
    handleSpec(options, extras)
  File "c:\users\chris\documents\github\bikeshed\bikeshed\cli.py", line 467, in handleSpec
    doc.preprocess()
  File "c:\users\chris\documents\github\bikeshed\bikeshed\Spec.py", line 137, in preprocess
    self.processDocument()
  File "c:\users\chris\documents\github\bikeshed\bikeshed\Spec.py", line 299, in processDocument
    extensions.BSPrepTR(self)  # pylint: disable=no-member
  File "<string>", line 2, in BSPrepTR
NameError: name 'findAll' is not defined

Chris@Nomad MINGW64 ~/Documents/GitHub/csswg-drafts/css-color-4 (main)
$ bikeshed -l spec
Traceback (most recent call last):
  File "C:\Python38\Scripts\bikeshed-script.py", line 33, in <module>
    sys.exit(load_entry_point('bikeshed', 'console_scripts', 'bikeshed')())
  File "c:\users\chris\documents\github\bikeshed\bikeshed\cli.py", line 412, in main
    handleSpec(options, extras)
  File "c:\users\chris\documents\github\bikeshed\bikeshed\cli.py", line 467, in handleSpec
    doc.preprocess()
  File "c:\users\chris\documents\github\bikeshed\bikeshed\Spec.py", line 137, in preprocess
    self.processDocument()
  File "c:\users\chris\documents\github\bikeshed\bikeshed\Spec.py", line 299, in processDocument
    extensions.BSPrepTR(self)  # pylint: disable=no-member
  File "<string>", line 2, in BSPrepTR
NameError: name 'findAll' is not defined

Chris@Nomad MINGW64 ~/Documents/GitHub/csswg-drafts/css-color-4 (main)
$ bikeshed -f spec
Traceback (most recent call last):
  File "C:\Python38\Scripts\bikeshed-script.py", line 33, in <module>
    sys.exit(load_entry_point('bikeshed', 'console_scripts', 'bikeshed')())
  File "c:\users\chris\documents\github\bikeshed\bikeshed\cli.py", line 412, in main
    handleSpec(options, extras)
  File "c:\users\chris\documents\github\bikeshed\bikeshed\cli.py", line 467, in handleSpec
    doc.preprocess()
  File "c:\users\chris\documents\github\bikeshed\bikeshed\Spec.py", line 137, in preprocess
    self.processDocument()
  File "c:\users\chris\documents\github\bikeshed\bikeshed\Spec.py", line 299, in processDocument
    extensions.BSPrepTR(self)  # pylint: disable=no-member
  File "<string>", line 2, in BSPrepTR
NameError: name 'findAll' is not defined
```

**Comment by tabatkins** [comment]
...literally that file it's apparently calling doesn't exist anymore. And you have a completely fresh install and an update that refreshed everything, so there's no chance you have an old version hanging around.

*This* suggests, then, that your `bikeshed` command might be running something different than what you expect, some old version installed from elsewhere?

If you run `type bikeshed`, does it report the path you expect? If not, try running `hash -r` and then trying it one more time. (Source: <https://unix.stackexchange.com/a/5610/214404>; I've run into this myself once.)

**Comment by svgeesus** [comment]
```
Chris@Nomad MINGW64 ~/Documents/GitHub/csswg-drafts/css-color-4 (main)
$ type bikeshed
bikeshed is hashed (/c/Python38/Scripts/bikeshed)

Chris@Nomad MINGW64 ~/Documents/GitHub/csswg-drafts/css-color-4 (main)
$ hash -r

Chris@Nomad MINGW64 ~/Documents/GitHub/csswg-drafts/css-color-4 (main)
$ bikeshed spec
Traceback (most recent call last):
  File "C:\Python38\Scripts\bikeshed-script.py", line 33, in <module>
    sys.exit(load_entry_point('bikeshed', 'console_scripts', 'bikeshed')())
  File "c:\users\chris\documents\github\bikeshed\bikeshed\cli.py", line 412, in main
    handleSpec(options, extras)
  File "c:\users\chris\documents\github\bikeshed\bikeshed\cli.py", line 467, in handleSpec
    doc.preprocess()
  File "c:\users\chris\documents\github\bikeshed\bikeshed\Spec.py", line 137, in preprocess
    self.processDocument()
  File "c:\users\chris\documents\github\bikeshed\bikeshed\Spec.py", line 299, in processDocument
    extensions.BSPrepTR(self)  # pylint: disable=no-member
  File "<string>", line 2, in BSPrepTR
NameError: name 'findAll' is not defined

```

**Comment by tabatkins** [comment]
Okay, if you go into `bikeshed/bikeshed/spec-data/boilerplate/csswg`, do you see a `bs-extensions.include` file?

**Comment by svgeesus** [comment]
```
Chris@Nomad MINGW64 ~/Documents/GitHub/csswg-drafts/css-color-4 (main)
$ which bikeshed
/c/Python38/Scripts/bikeshed

Chris@Nomad MINGW64 ~/Documents/GitHub/csswg-drafts/css-color-4 (main)
$ pushd /c/Python38/Scripts/
/c/Python38/Scripts ~/Documents/GitHub/csswg-drafts/css-color-4

Chris@Nomad MINGW64 /c/Python38/Scripts
$ ls
bikeshed-script.py*  easy_install-3.8.exe*  normalizer.exe*  pip3.exe*
bikeshed.exe*        easy_install.exe*      pip.exe*         pygmentize.exe*
chardetect.exe*      f2py.exe*              pip3.8.exe*      tqdm.exe*

Chris@Nomad MINGW64 /c/Python38/Scripts
$ rm bik*

Chris@Nomad MINGW64 /c/Python38/Scripts
$ popd
~/Documents/GitHub/csswg-drafts/css-color-4

Chris@Nomad MINGW64 ~/Documents/GitHub/csswg-drafts/css-color-4 (main)
$ cd ../../bikeshed

Chris@Nomad MINGW64 ~/Documents/GitHub/bikeshed (main)
$ pip install -e .
Obtaining file:///C:/Users/Chris/Documents/GitHub/bikeshed
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: lxml==4.8.0 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (4.8.0)
Requirement already satisfied: certifi==2021.10.8 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (2021.10.8)
Requirement already satisfied: pillow==9.0.1 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (9.0.1)
Requirement already satisfied: isodate==0.6.1 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (0.6.1)
Requirement already satisfied: json-home-client==1.1.1 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (1.1.1)
Requirement already satisfied: uri-template==1.1.0 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (1.1.0)
Requirement already satisfied: idna==3.3 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (3.3)
Requirement already satisfied: result==0.7.0 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (0.7.0)
Requirement already satisfied: typing-extensions==4.1.1 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (4.1.1)
Requirement already satisfied: multidict==6.0.2 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (6.0.2)
Requirement already satisfied: requests==2.27.1 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (2.27.1)
Requirement already satisfied: charset-normalizer==2.0.12 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (2.0.12)
Requirement already satisfied: yarl==1.7.2 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (1.7.2)
Requirement already satisfied: html5lib==1.1 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (1.1)
Requirement already satisfied: frozenlist==1.3.0 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (1.3.0)
Requirement already satisfied: cssselect==1.1.0 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (1.1.0)
Requirement already satisfied: aiofiles==0.8.0 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (0.8.0)
Requirement already satisfied: pygments==2.11.2 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (2.11.2)
Requirement already satisfied: webencodings==0.5.1 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (0.5.1)
Requirement already satisfied: urllib3==1.26.8 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (1.26.8)
Requirement already satisfied: attrs==21.4.0 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (21.4.0)
Requirement already satisfied: widlparser==1.0.12 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (1.0.12)
Requirement already satisfied: aiosignal==1.2.0 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (1.2.0)
Requirement already satisfied: six==1.16.0 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (1.16.0)
Requirement already satisfied: aiohttp==3.8.1 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (3.8.1)
Requirement already satisfied: tenacity==8.0.1 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (8.0.1)
Requirement already satisfied: async-timeout==4.0.2 in c:\python38\lib\site-packages (from bikeshed==3.4.3) (4.0.2)
Installing collected packages: bikeshed
  Attempting uninstall: bikeshed
    Found existing installation: bikeshed 3.4.3
    Uninstalling bikeshed-3.4.3:
      Successfully uninstalled bikeshed-3.4.3
  Running setup.py develop for bikeshed
Successfully installed bikeshed-3.4.3

Chris@Nomad MINGW64 ~/Documents/GitHub/bikeshed (main)
$ bikeshed update
Updating via manifest...
Gathering local manifest data...
Fetching remote manifest data...
Local data is already up-to-date with remote (2022-04-21 22:16:41)

Chris@Nomad MINGW64 ~/Documents/GitHub/bikeshed (main)
$ popd
bash: popd: directory stack empty

Chris@Nomad MINGW64 ~/Documents/GitHub/bikeshed (main)
$ cd ../csswg-drafts/css-color-4

Chris@Nomad MINGW64 ~/Documents/GitHub/csswg-drafts/css-color-4 (main)
$ bikeshed spec
Traceback (most recent call last):
  File "C:\Python38\Scripts\bikeshed-script.py", line 33, in <module>
    sys.exit(load_entry_point('bikeshed', 'console_scripts', 'bikeshed')())
  File "c:\users\chris\documents\github\bikeshed\bikeshed\cli.py", line 412, in main
    handleSpec(options, extras)
  File "c:\users\chris\documents\github\bikeshed\bikeshed\cli.py", line 467, in handleSpec
    doc.preprocess()
  File "c:\users\chris\documents\github\bikeshed\bikeshed\Spec.py", line 137, in preprocess
    self.processDocument()
  File "c:\users\chris\documents\github\bikeshed\bikeshed\Spec.py", line 299, in processDocument
    extensions.BSPrepTR(self)  # pylint: disable=no-member
  File "<string>", line 2, in BSPrepTR
NameError: name 'findAll' is not defined

```

**Comment by svgeesus** [comment]
> Okay, if you go into bikeshed/bikeshed/spec-data/boilerplate/csswg, do you see a bs-extensions.include file?

Yes

```
Chris@Nomad MINGW64 ~/Documents/GitHub/csswg-drafts/css-color-4 (main)
$ cd ../../bikeshed/bikeshed/spec-data/boilerplate/csswg

Chris@Nomad MINGW64 ~/Documents/GitHub/bikeshed/bikeshed/spec-data/boilerplate/csswg (main)
$ ls
abstract.include           defaults-ED.include     header.include
bs-extensions.include      defaults.include        status.include
computed-metadata.include  footer-WG-NOTE.include  warning-not-ready.include
copyright-DREAM.include    footer.include          warning-obsolete.include


```

**Comment by tabatkins** [comment]
What the *fuck*.  Could you delete it, and run `bikeshed update` again, then check if it reappears?

**Comment by svgeesus** [comment]
It does not reappear

```
Chris@Nomad MINGW64 ~/Documents/GitHub/bikeshed/bikeshed/spec-data/boilerplate/csswg (main)
$ rm bs-extensions.include

Chris@Nomad MINGW64 ~/Documents/GitHub/bikeshed/bikeshed/spec-data/boilerplate/csswg (main)
$ bikeshed update
Updating via manifest...
Gathering local manifest data...
Fetching remote manifest data...
Local data is already up-to-date with remote (2022-04-21 22:16:41)

Chris@Nomad MINGW64 ~/Documents/GitHub/bikeshed/bikeshed/spec-data/boilerplate/csswg (main)
$ ls
abstract.include           defaults.include        status.include
computed-metadata.include  footer-WG-NOTE.include  warning-not-ready.include
copyright-DREAM.include    footer.include          warning-obsolete.include
defaults-ED.include        header.include
```

**Comment by tabatkins** [comment]
OKAY. So, first, your bikeshed should now work correctly. This means I *do* have a bug in my "delete old files that are no longer in the manifest" code, tho, which is frustrating. Sorry about that.

**Comment by svgeesus** [comment]
Aaand that fixed it

```
Chris@Nomad MINGW64 ~/Documents/GitHub/bikeshed/bikeshed (main)
$ cd ../../csswg-drafts/css-color-4

Chris@Nomad MINGW64 ~/Documents/GitHub/csswg-drafts/css-color-4 (main)
$ bikeshed spec
```

Thanks for the real-time help, @tabatkins  !!

**Comment by tabatkins** [comment]
Thanks for the realtime debugging!
