### ISSUE TITLE
Crash when preparing CSS Color 4 for CR (in addBikeshedVersion)

### ISSUE THREAD

**Issue by svgeesus** [tabatkins/bikeshed#2307]
In preparation for publishing the CR I updated my clone of the bikeshed repo, installed, updated

```
git pull
pip install -e .
bikeshed update
```

Now I get a crash with `bikeshed spec`:

```
Chris@Nomad MINGW64 ~/Documents/GitHub/csswg-drafts/css-color-4 (main)
$ bikeshed spec
Traceback (most recent call last):
  File "c:\users\chris\documents\github\bikeshed\bikeshed\boilerplate.py", line 46, in addBikeshedVersion
    subprocess.check_output(
  File "C:\Python38\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'git log -1 --format='Bikeshed version %h, updated %cd'' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\Scripts\bikeshed-script.py", line 33, in <module>
    sys.exit(load_entry_point('bikeshed', 'console_scripts', 'bikeshed')())
  File "c:\users\chris\documents\github\bikeshed\bikeshed\cli.py", line 422, in main
    handleSpec(options, extras)
  File "c:\users\chris\documents\github\bikeshed\bikeshed\cli.py", line 477, in handleSpec
    doc.preprocess()
  File "c:\users\chris\documents\github\bikeshed\bikeshed\Spec.py", line 137, in preprocess
    self.processDocument()
  File "c:\users\chris\documents\github\bikeshed\bikeshed\Spec.py", line 213, in processDocument
    boilerplate.addBikeshedVersion(self)
  File "c:\users\chris\documents\github\bikeshed\bikeshed\boilerplate.py", line 57, in addBikeshedVersion
    bikeshedVersion = doc.dataFile.fetch("bikeshed-version.txt", type="readonly", str=True).strip()
TypeError: fetch() got an unexpected keyword argument 'type'
```

**Comment by tabatkins** [comment]
Oh funky, that particular codepath isn't exercised by any of my test code, so I missed that I'd gotten the keyword argument wrong. Fixed things up, should be good now.
