### ISSUE TITLE
error during bikeshed update: The 'typing-extensions==4.3.0' distribution was not found and is required by bikeshed

### ISSUE THREAD

**Issue by dbaron** [tabatkins/bikeshed#2334]
I have a script that updates and installs bikeshed every morning with the command:

```sh
(cd ~/builds/bikeshed/ && git pull && pip3 install --upgrade --prefix="${HOME}/.local/" -e . && bikeshed update)
```

I just updated the machine that this runs on from Ubuntu 20.04.4 to Ubuntu 22.04.1.  This causes the `bikeshed update` part of the above to fail with the following output:

```
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.16.0-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Traceback (most recent call last):
  File "/home/dbaron/.local/bin/bikeshed", line 33, in <module>
    sys.exit(load_entry_point('bikeshed', 'console_scripts', 'bikeshed')())
  File "/home/dbaron/.local/bin/bikeshed", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dbaron/builds/bikeshed/bikeshed/__init__.py", line 63, in <module>
    verify_requirements()
  File "/home/dbaron/builds/bikeshed/bikeshed/__init__.py", line 36, in verify_requirements
    import pkg_resources
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3267, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3241, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'typing-extensions==4.3.0' distribution was not found and is required by bikeshed
```

Installing the Ubuntu package with `sudo apt install python3-typing-extensions` (which installs version `3.10.0.2-1`) doesn't make a difference.

**Comment by tabatkins** [comment]
...huh, that's odd. What's the output of your `pip3 install`? `typing-extensions==4.3.0` is in `requirements.txt`, and should be picked up by the install; if it's not, *nothing else* should be picked up either.

**Comment by dbaron** [comment]
The output is:

```
Obtaining file:///home/dbaron/builds/bikeshed
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting result==0.8.0
  Using cached result-0.8.0-py3-none-any.whl (7.9 kB)
Collecting certifi==2022.6.15
  Using cached certifi-2022.6.15-py3-none-any.whl (160 kB)
Collecting aiofiles==0.8.0
  Using cached aiofiles-0.8.0-py3-none-any.whl (13 kB)
Requirement already satisfied: html5lib==1.1 in /usr/lib/python3/dist-packages (from bikeshed==3.7.4) (1.1)
Collecting typing-extensions==4.3.0
  Using cached typing_extensions-4.3.0-py3-none-any.whl (25 kB)
Collecting requests==2.28.1
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting yarl==1.7.2
  Using cached yarl-1.7.2-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (305 kB)
Requirement already satisfied: pygments==2.11.2 in /usr/lib/python3/dist-packages (from bikeshed==3.7.4) (2.11.2)
Collecting multidict==6.0.2
  Using cached multidict-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
Collecting json-home-client==1.1.1
  Using cached json_home_client-1.1.1-py3-none-any.whl (9.7 kB)
Collecting aiohttp==3.8.1
  Using cached aiohttp-3.8.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.2 MB)
Collecting uri-template==1.2.0
  Using cached uri_template-1.2.0-py3-none-any.whl (10 kB)
Collecting tenacity==8.0.1
  Using cached tenacity-8.0.1-py3-none-any.whl (24 kB)
Collecting urllib3==1.26.11
  Using cached urllib3-1.26.11-py2.py3-none-any.whl (139 kB)
Collecting isodate==0.6.1
  Using cached isodate-0.6.1-py2.py3-none-any.whl (41 kB)
Collecting frozenlist==1.3.0
  Using cached frozenlist-1.3.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (157 kB)
Collecting widlparser==1.1.1
  Using cached widlparser-1.1.1-py3-none-any.whl (35 kB)
Collecting attrs==21.4.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting aiosignal==1.2.0
  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting charset-normalizer==2.1.0
  Using cached charset_normalizer-2.1.0-py3-none-any.whl (39 kB)
Requirement already satisfied: pillow==9.0.1 in /usr/lib/python3/dist-packages (from bikeshed==3.7.4) (9.0.1)
Collecting async-timeout==4.0.2
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Requirement already satisfied: webencodings==0.5.1 in /usr/lib/python3/dist-packages (from bikeshed==3.7.4) (0.5.1)
Requirement already satisfied: idna==3.3 in /usr/lib/python3/dist-packages (from bikeshed==3.7.4) (3.3)
Collecting lxml==4.9.1
  Using cached lxml-4.9.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (6.9 MB)
Requirement already satisfied: six==1.16.0 in /usr/lib/python3/dist-packages (from bikeshed==3.7.4) (1.16.0)
Collecting cssselect==1.1.0
  Using cached cssselect-1.1.0-py2.py3-none-any.whl (16 kB)
Installing collected packages: urllib3, uri-template, typing-extensions, tenacity, result, multidict, lxml, isodate, frozenlist, cssselect, charset-normalizer, certifi, attrs, async-timeout, aiofiles, yarl, widlparser, requests, json-home-client, aiosignal, aiohttp, bikeshed
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.5
    Not uninstalling urllib3 at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'urllib3'. No files were found to uninstall.
  Attempting uninstall: lxml
    Found existing installation: lxml 4.8.0
    Not uninstalling lxml at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'lxml'. No files were found to uninstall.
  Attempting uninstall: certifi
    Found existing installation: certifi 2020.6.20
    Not uninstalling certifi at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'certifi'. No files were found to uninstall.
  Attempting uninstall: attrs
    Found existing installation: attrs 21.2.0
    Not uninstalling attrs at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'attrs'. No files were found to uninstall.
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Not uninstalling requests at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'requests'. No files were found to uninstall.
  Attempting uninstall: bikeshed
    Found existing installation: bikeshed 3.7.4
    Uninstalling bikeshed-3.7.4:
      Successfully uninstalled bikeshed-3.7.4
  Running setup.py develop for bikeshed
Successfully installed aiofiles-0.8.0 aiohttp-3.8.1 aiosignal-1.2.0 async-timeout-4.0.2 attrs-21.4.0 bikeshed certifi-2022.6.15 charset-normalizer-2.1.0 cssselect-1.1.0 frozenlist-1.3.0 isodate-0.6.1 json-home-client-1.1.1 lxml-4.9.1 multidict-6.0.2 requests-2.28.1 result-0.8.0 tenacity-8.0.1 typing-extensions-4.3.0 uri-template-1.2.0 urllib3-1.26.11 widlparser-1.1.1 yarl-1.7.2
```

**Comment by dbaron** [comment]
So this was fixable with `export PYTHONPATH=/home/dbaron/.local/local/lib/python3.10/dist-packages`... which was never needed in the past.  (I'm not sure what the convention behind `.local` is, actually...)

**Comment by dbaron** [comment]
I guess this is just a side-effect of my workaround for the `--user` argument to `pip3 install` being completely ignored, despite being clearly documented.
