### ISSUE TITLE
Bikeshed won't run (Ubuntu), gives traceback

### ISSUE THREAD

**Issue by svgeesus** [tabatkins/bikeshed#2339]
Context: New Windows computer, decided to use bash/python/git/cvs/bikeshed etc from the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install), which basically installs Ubuntu inside Windows and gives you a real Linux environment. (I had previously done all that from [cygwin](https://www.cygwin.com/)).

Following [Installing Bikeshed for Development](https://tabatkins.github.io/bikeshed/#install-dev) everything looked fine. I did

```
git pull
sudo pip3 install -e .
```

inside the checked-out Bikeshed repo, and that looked fine. Then

```
chris@SuperNomad:/mnt/c/Users/chris/Documents/GitHub/bikeshed$ which bikeshed
/usr/bin/bikeshed
chris@SuperNomad:/mnt/c/Users/chris/Documents/GitHub/bikeshed$ bikeshed update
Traceback (most recent call last):
  File "/usr/bin/bikeshed", line 33, in <module>
    sys.exit(load_entry_point('bikeshed', 'console_scripts', 'bikeshed')())
  File "/usr/bin/bikeshed", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: bikeshed
```

Same stack trace for any other bikeshed command, like `bikeshed spec`.

**Comment by svgeesus** [comment]
OK so firstly, I had installed using sudo because when I didn't, I got an error that the place it installed bikeshed (~/.local/bin) was not on my PATH.

However, I have now solved this, with

```
pip3 install -e .
bikeshed update
```

`which bikeshed` still tells me it is in /usr/bin but now, it doesn't crash.

I don't understand this but am up and running so, I guess this issue can be closed.
