### ISSUE TITLE
crash when using user install

### ISSUE THREAD

**Issue by nektro** [tabatkins/bikeshed#2343]
```
[nix-shell:]$ pip install --user bikeshed
Collecting bikeshed
  Using cached bikeshed-3.7.4-py3-none-any.whl (10.7 MB)
Collecting isodate==0.6.1
  Using cached isodate-0.6.1-py2.py3-none-any.whl (41 kB)
Collecting pygments==2.11.2
  Using cached Pygments-2.11.2-py3-none-any.whl (1.1 MB)
Collecting urllib3==1.26.11
  Using cached urllib3-1.26.11-py2.py3-none-any.whl (139 kB)
Collecting typing-extensions==4.3.0
  Using cached typing_extensions-4.3.0-py3-none-any.whl (25 kB)
Collecting aiofiles==0.8.0
  Using cached aiofiles-0.8.0-py3-none-any.whl (13 kB)
Collecting result==0.8.0
  Using cached result-0.8.0-py3-none-any.whl (7.9 kB)
Collecting idna==3.3
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting lxml==4.9.1
  Using cached lxml-4.9.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (7.0 MB)
Collecting requests==2.28.1
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting json-home-client==1.1.1
  Using cached json_home_client-1.1.1-py3-none-any.whl (9.7 kB)
Collecting tenacity==8.0.1
  Using cached tenacity-8.0.1-py3-none-any.whl (24 kB)
Collecting webencodings==0.5.1
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting frozenlist==1.3.0
  Using cached frozenlist-1.3.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (156 kB)
Collecting attrs==21.4.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting pillow==9.0.1
  Using cached Pillow-9.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.3 MB)
Collecting multidict==6.0.2
  Using cached multidict-6.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
Collecting yarl==1.7.2
  Using cached yarl-1.7.2-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (304 kB)
Collecting aiosignal==1.2.0
  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting html5lib==1.1
  Using cached html5lib-1.1-py2.py3-none-any.whl (112 kB)
Collecting aiohttp==3.8.1
  Using cached aiohttp-3.8.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.2 MB)
Collecting cssselect==1.1.0
  Using cached cssselect-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting async-timeout==4.0.2
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting charset-normalizer==2.1.0
  Using cached charset_normalizer-2.1.0-py3-none-any.whl (39 kB)
Collecting certifi==2022.6.15
  Using cached certifi-2022.6.15-py3-none-any.whl (160 kB)
Collecting six==1.16.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting uri-template==1.2.0
  Using cached uri_template-1.2.0-py3-none-any.whl (10 kB)
Collecting widlparser==1.1.1
  Using cached widlparser-1.1.1-py3-none-any.whl (35 kB)
Installing collected packages: webencodings, urllib3, uri-template, typing-extensions, tenacity, six, pygments, pillow, multidict, lxml, idna, frozenlist, cssselect, charset-normalizer, certifi, attrs, async-timeout, aiofiles, yarl, widlparser, result, requests, json-home-client, isodate, html5lib, aiosignal, aiohttp, bikeshed
Successfully installed aiofiles-0.8.0 aiohttp-3.8.1 aiosignal-1.2.0 async-timeout-4.0.2 attrs-21.4.0 bikeshed-3.7.4 certifi-2022.6.15 charset-normalizer-2.1.0 cssselect-1.1.0 frozenlist-1.3.0 html5lib-1.1 idna-3.3 isodate-0.6.1 json-home-client-1.1.1 lxml-4.9.1 multidict-6.0.2 pillow-9.0.1 pygments-2.11.2 requests-2.28.1 result-0.8.0 six-1.16.0 tenacity-8.0.1 typing-extensions-4.3.0 uri-template-1.2.0 urllib3-1.26.11 webencodings-0.5.1 widlparser-1.1.1 yarl-1.7.2
WARNING: You are using pip version 22.0.4; however, version 22.2.2 is available.
You should consider upgrading via the '/nix/store/65h1mb8604dbw077762j702q6b8i0mpw-python3-3.9.13/bin/python3.9 -m pip install --upgrade pip' command.
```

```
[nix-shell:]$ bikeshed update
Traceback (most recent call last):
  File "/home/meghan/.local/bin/bikeshed", line 5, in <module>
    from bikeshed import main
ModuleNotFoundError: No module named 'bikeshed'
```

```
[nix-shell:]$ bikeshed spec
Traceback (most recent call last):
  File "/home/meghan/.local/bin/bikeshed", line 5, in <module>
    from bikeshed import main
ModuleNotFoundError: No module named 'bikeshed'
```

**Comment by tabatkins** [comment]
Yeah, it looks like pip and Nix don't natively work well together; see <https://www.reddit.com/r/NixOS/comments/q71v0e/what_is_the_correct_way_to_setup_pip_with_nix_to/> for explanations and workarounds.

**Comment by nektro** [comment]
its available as `nix-shell -p bikeshed` for the curious

**Comment by nektro** [comment]
didnt find it under `python.pkgs.bikeshed` but discovered the top level package with `nix-locate` as i should have the first time around, sorry for the noise
