### ISSUE TITLE
Streams spec is broken with Python error now

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#471]
```
curl https://api.csswg.org/bikeshed/ -F md-Text-Macro="SNAPSHOT-LINK dummy" -F file=@index.bs > index.tmp.html
```

output contains

```
Error running preprocessor, returned code: 1.
Traceback (most recent call last):
  File "/sites/api.csswg.org/bikeshed/bikeshed.py", line 5, in <module>
    bikeshed.main()
  File "/sites/api.csswg.org/bikeshed/bikeshed/__init__.py", line 178, in main
    doc.finish(outputFilename=options.outfile)
  File "/sites/api.csswg.org/bikeshed/bikeshed/__init__.py", line 1465, in finish
    rendered = self.serialize()
  File "/sites/api.csswg.org/bikeshed/bikeshed/__init__.py", line 1446, in serialize
    rendered = HTMLSerializer.HTMLSerializer(self.document, self.md.opaqueElements).serialize()
  File "/sites/api.csswg.org/bikeshed/bikeshed/HTMLSerializer.py", line 22, in serialize
    self._serializeEl(root, writer)
  File "/sites/api.csswg.org/bikeshed/bikeshed/HTMLSerializer.py", line 132, in _serializeEl
    self._serializeEl(block, write, indent=indent+1)
  File "/sites/api.csswg.org/bikeshed/bikeshed/HTMLSerializer.py", line 132, in _serializeEl
    self._serializeEl(block, write, indent=indent+1)
  File "/sites/api.csswg.org/bikeshed/bikeshed/HTMLSerializer.py", line 132, in _serializeEl
    self._serializeEl(block, write, indent=indent+1)
  File "/sites/api.csswg.org/bikeshed/bikeshed/HTMLSerializer.py", line 132, in _serializeEl
    self._serializeEl(block, write, indent=indent+1)
  File "/sites/api.csswg.org/bikeshed/bikeshed/HTMLSerializer.py", line 108, in _serializeEl
    blocks = [block for block in groupIntoBlocks(childNodes(el)) if not justWS(block)]
  File "/sites/api.csswg.org/bikeshed/bikeshed/HTMLSerializer.py", line 104, in justWS
    return len(block) == 1 and block[0].strip() == ""
AttributeError: 'lxml.etree._Element' object has no attribute 'strip'
```

At least I'm no longer deploying that error to streams.spec.whatwg.org....

**Comment by tabatkins** [comment]
FUCK

**Comment by tabatkins** [comment]
Fixed.  Ugh, I hate writing code while massively distracted.
