### ISSUE TITLE
IndexError when trying to process enum with ""

### ISSUE THREAD

**Issue by arronei** [tabatkins/bikeshed#692]
```
Traceback (most recent call last):
  File "C:\Python27\Scripts\bikeshed-script.py", line 9, in <module>
    load_entry_point('Bikeshed==0.0.0', 'console_scripts', 'bikeshed')()
  File "d:\github\bikeshed-arronei\bikeshed\__init__.py", line 171, in main
    doc.preprocess()
  File "d:\github\bikeshed-arronei\bikeshed\__init__.py", line 502, in preprocess
    processIDL(self)
  File "d:\github\bikeshed-arronei\bikeshed\__init__.py", line 1716, in processIDL
    error=False)
  File "d:\github\bikeshed-arronei\bikeshed\ReferenceManager.py", line 221, in getRef
    variedTexts = [v for v in linkTextVariations(text, linkType) if v in self.defaultSpecs]
  File "d:\github\bikeshed-arronei\bikeshed\ReferenceManager.py", line 631, in linkTextVariations
    if str[0] != "_":
IndexError: string index out of range
```
I think we need a special case for this because how would I link to the value dfn for ""?

```html
<pre class='metadata'>
Title: Test
Status: WD
TR: http://www.w3.org/TR/SpecName/
ED: http://www.w3.org/TR/SpecName
Previous Version: http://www.w3.org/TR/SpecName
Shortname: SpecName
Level: 1
Editor: John Doe, AnOrg., AnOrg@mail.com
Abstract: Abstract sentence
</pre>

<pre class="idl" data-highlight="webidl" dfn-for="CanPlayTypeResult">
enum CanPlayTypeResult { "" /* empty string */, "maybe", "probably" };
</pre>
```

**Comment by tabatkins** [comment]
Fixed!  Sorry for the delay; I was on vacation.

Random note: there's no need for `data-highlight="webidl"` (it does nothing, because the existing WebIDL parser puts markup into the `<pre>`, and the highlighter bails if there's any markup, because it wipes out markup), and the `dfn-for` is actually *wrong*, not just unnecessary (the parser sets up all your `for` values correctly; all your manual `dfn-for` does is add a `for` value to the definitions of top-level things like "interface" or "enum", which is clearly wrong).
