### ISSUE TITLE
FATAL: api.csswg.org/bikeshed now choking on known-good input spec source 

### ISSUE THREAD

**Issue by equalsJeffH** [tabatkins/bikeshed#725]
bikeshed correctly processed https://github.com/w3c/webauthn/blob/master/index.src.html on 1-Jun-2016, but is now choking on that exact file...
```
> curl https://api.csswg.org/bikeshed/ -F file=@index.src.html -F force=1 -F output=err > errors.txt ; ls -l errors* ; cat errors.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  112k    0  1027  100  111k   1635   177k --:--:-- --:--:-- --:--:--  178k
-rw-r--r--  1 .........  .........  1027 Jun 14 13:39 errors.txt
Error running preprocessor, returned code: 1.
Traceback (most recent call last):
  File "/sites/api.csswg.org/bikeshed/bikeshed.py", line 5, in 
    bikeshed.main()
  File "/sites/api.csswg.org/bikeshed/bikeshed/__init__.py", line 191, in main
    doc.preprocess()
  File "/sites/api.csswg.org/bikeshed/bikeshed/__init__.py", line 499, in preprocess
    self.lines, documentMd = metadata.parse(lines=self.lines, doc=self)
  File "/sites/api.csswg.org/bikeshed/bikeshed/MetadataManager.py", line 558, in parse
    md.addData(match.group(1), match.group(2), lineNum=i+1)
  File "/sites/api.csswg.org/bikeshed/bikeshed/MetadataManager.py", line 109, in addData
    val = md.parse(key, val, lineNum)
  File "/sites/api.csswg.org/bikeshed/bikeshed/MetadataManager.py", line 256, in parseLevel
    return config.HierarchicalNumber(val)
  File "/sites/api.csswg.org/bikeshed/bikeshed/config.py", line 156, in __init__
    self.nums = [int(x) for x in re.split(r"\D+", valString)]
ValueError: invalid literal for int() with base 10: ''
```

**Comment by tabatkins** [comment]
It's the empty level that's doing it.  (It should be emitting a fatal error, not a Python crash, so I've still got a bug to fix here.)

I recently standardized on a method to actually handle unlevelled specs - use `Level: none`.

**Comment by equalsJeffH** [comment]
ah, you mean "Level: " within the `<pre class='metadata'>` block.   thanks.
