### ISSUE TITLE
Markup in highlighted code breaks parsing

### ISSUE THREAD

**Issue by SebastianZ** [tabatkins/bikeshed#726]
E.g. `<a>` or `<br>` tags within `<pre>` blocks cause the parsing to fail with the following error trace:

```
Traceback (most recent call last):
  File "/sites/api.csswg.org/bikeshed/bikeshed.py", line 5, in 
    bikeshed.main()
  File "/sites/api.csswg.org/bikeshed/bikeshed/__init__.py", line 192, in main
    doc.preprocess()
  File "/sites/api.csswg.org/bikeshed/bikeshed/__init__.py", line 579, in preprocess
    addSyntaxHighlighting(self)
  File "/sites/api.csswg.org/bikeshed/bikeshed/__init__.py", line 1913, in addSyntaxHighlighting
    highlight(el, translateLang(lang))
  File "/sites/api.csswg.org/bikeshed/bikeshed/__init__.py", line 1884, in highlight
    mergeHighlighting(el, highlighted)
  File "/sites/api.csswg.org/bikeshed/bikeshed/__init__.py", line 2037, in mergeHighlighting
    colorizeEl(el, coloredText)
  File "/sites/api.csswg.org/bikeshed/bikeshed/__init__.py", line 2007, in colorizeEl
    appendChild(el, *colorizeText(node, coloredText))
  File "/sites/api.csswg.org/bikeshed/bikeshed/__init__.py", line 2013, in colorizeText
    if len(nextColor.text) <= len(text):
TypeError: object of type 'NoneType' has no len()
```

See https://drafts.csswg.org/bikeshed/css-flexbox/ as an example.

Sebastian

**Comment by tabatkins** [comment]
Yeah, @plinss told me about this yesterday. I simply cannot reproduce it locally, either on my work machine or my laptop, tho. :/

**Comment by plinss** [comment]
FWIW I can reproduce on my dev VM (Debian, same software as csswg.org), so it's not likely something weird on the server...

**Comment by tabatkins** [comment]
What's your Pygments version? I have 

```
$ pygmentize -V
Pygments version 1.6, (c) 2006-2013 by Georg Brandl.
```

**Comment by plinss** [comment]
$ pygmentize -V
Pygments version 2.1.3, (c) 2006-2015 by Georg Brandl.

**Comment by tabatkins** [comment]
WELL THAT'S PROBABLY THE ISSUE THEN

(How the fuck did I get such an old version???)

**Comment by plinss** [comment]
¯\_(ツ)_/¯

**Comment by tabatkins** [comment]
And yup, I can now reproduce. Okay, I'll get to fixing.

**Comment by tabatkins** [comment]
Fixed. Newer Pygments for some reason sometimes emits an empty span at the start of a highlighted block? I'm guessing it has something to do with my CSS language definition; the treatment of it must have changed slightly between versions.

**Comment by SebastianZ** [comment]
Perfect, thank you!

Sebastian
