### ISSUE TITLE
Runtime error after moving highlight code out to a separate file

### ISSUE THREAD

**Issue by jungkees** [tabatkins/bikeshed#867]
I encountered a runtime error when running "bikeshed -f spec" as follows:

```
Traceback (most recent call last):
  File "/usr/local/bin/bikeshed", line 9, in <module>
    load_entry_point('Bikeshed==0.0.0', 'console_scripts', 'bikeshed')()
  File "/home/jungkees/git/bikeshed/bikeshed/__init__.py", line 196, in main
    doc.preprocess()
  File "/home/jungkees/git/bikeshed/bikeshed/__init__.py", line 590, in preprocess
    highlight.addSyntaxHighlighting(self)
  File "/home/jungkees/git/bikeshed/bikeshed/highlight.py", line 85, in addSyntaxHighlighting
    highlight(el, translateLang(lang))
  File "/home/jungkees/git/bikeshed/bikeshed/highlight.py", line 27, in highlight
    widl = parser.Parser(text, IDLUI())
NameError: global name 'parser' is not defined
```

It seems it comes after b56c81b533641bb68ecfcdea3d0435fc56b213f2. Importing parser, accessing class IDLUI, etc. seem to be needed.

**Comment by tobie** [comment]
CI seems unhappy, too.

**Comment by tabatkins** [comment]
Done, sorry about that.
