### ISSUE TITLE
Running Bikeshed on xhr.bs results in an infinite loop

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#936]
```console
bikeshed spec xhr.bs xhr.html --md-Text-Macro="SNAPSHOT-LINK LOCAL COPY"
Traceback (most recent call last):
  File "/usr/local/bin/bikeshed", line 9, in <module>
    load_entry_point('Bikeshed==0.0.0', 'console_scripts', 'bikeshed')()
  File "/Users/annevk/GH/bikeshed/bikeshed/__init__.py", line 214, in main
    doc.preprocess()
  File "/Users/annevk/GH/bikeshed/bikeshed/__init__.py", line 597, in preprocess
    processBiblioLinks(self)
  File "/Users/annevk/GH/bikeshed/bikeshed/__init__.py", line 1379, in processBiblioLinks
    ref = doc.refs.getBiblioRef(linkText, status=biblioStatus, generateFakeRef=okayToFail, el=el)
  File "/Users/annevk/GH/bikeshed/bikeshed/ReferenceManager.py", line 644, in getBiblioRef
    bib = self.getBiblioRef(candidate["aliasOf"], status=status, el=el, quiet=True)
  File "/Users/annevk/GH/bikeshed/bikeshed/ReferenceManager.py", line 644, in getBiblioRef
    bib = self.getBiblioRef(candidate["aliasOf"], status=status, el=el, quiet=True)
```
...
```console
  File "/Users/annevk/GH/bikeshed/bikeshed/ReferenceManager.py", line 644, in getBiblioRef
    bib = self.getBiblioRef(candidate["aliasOf"], status=status, el=el, quiet=True)
  File "/Users/annevk/GH/bikeshed/bikeshed/ReferenceManager.py", line 644, in getBiblioRef
    bib = self.getBiblioRef(candidate["aliasOf"], status=status, el=el, quiet=True)
  File "/Users/annevk/GH/bikeshed/bikeshed/ReferenceManager.py", line 644, in getBiblioRef
    bib = self.getBiblioRef(candidate["aliasOf"], status=status, el=el, quiet=True)
  File "/Users/annevk/GH/bikeshed/bikeshed/ReferenceManager.py", line 644, in getBiblioRef
    bib = self.getBiblioRef(candidate["aliasOf"], status=status, el=el, quiet=True)
  File "/Users/annevk/GH/bikeshed/bikeshed/ReferenceManager.py", line 644, in getBiblioRef
    bib = self.getBiblioRef(candidate["aliasOf"], status=status, el=el, quiet=True)
  File "/Users/annevk/GH/bikeshed/bikeshed/ReferenceManager.py", line 644, in getBiblioRef
    bib = self.getBiblioRef(candidate["aliasOf"], status=status, el=el, quiet=True)
  File "/Users/annevk/GH/bikeshed/bikeshed/ReferenceManager.py", line 644, in getBiblioRef
    bib = self.getBiblioRef(candidate["aliasOf"], status=status, el=el, quiet=True)
  File "/Users/annevk/GH/bikeshed/bikeshed/ReferenceManager.py", line 636, in getBiblioRef
    candidate = stripLineBreaks(sorted(candidates, key=itemgetter('order'))[0])
RuntimeError: maximum recursion depth exceeded in cmp
```
This started happening this morning per https://github.com/whatwg/xhr/commits but I can't really find an offending commit.

**Comment by annevk** [comment]
Same for fetch.bs.

**Comment by tobie** [comment]
I think this relates to a combination of [special casing certains references in BS](https://github.com/tabatkins/bikeshed/blob/f2fabcb/bikeshed/ReferenceManager.py#L611) and me starting to [fix](https://github.com/tobie/specref/commit/f4eac25cda3d5b46a9a86b24319154b7e9dbaf34) [some](https://github.com/tobie/specref/commit/265384cf3786a74481487f34fffa5b207d1c9973) in Specref yesterday.

**Comment by tobie** [comment]
So all 5 WHATWG references are now fixed in Specref, see: http://specref.herokuapp.com/bibrefs?refs=dom,url,encoding,fullscreen,notifications.

You should be able to just remove the above special casing, now.

**Comment by tabatkins** [comment]
All right, special-casing removed now.  I'll push an update to the initial data files, so if anyone downloads Bikeshed fresh (or pulls from git without running `bikeshed update`), they'll get the right refs.
