### ISSUE TITLE
bikeshed crashes when offline if linking to github issues

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#962]
Just tried to build Paint, which links to w3c/csswg-drafts/383, and it won't compile offline. :( Traceback hits a connection error.

**Comment by fantasai** [comment]
```
Fetching issue   1/1: w3c/csswg-drafts/383
Traceback (most recent call last):
  File "/home/fantasai/.local/bin/bikeshed", line 11, in <module>
    load_entry_point('Bikeshed', 'console_scripts', 'bikeshed')()
  File "/home/fantasai/w3c/bikeshed/bikeshed/__init__.py", line 214, in main
    doc.preprocess()
  File "/home/fantasai/w3c/bikeshed/bikeshed/__init__.py", line 594, in preprocess
    inlineRemoteIssues(self)
  File "/home/fantasai/w3c/bikeshed/bikeshed/__init__.py", line 2315, in inlineRemoteIssues
    res = requests.get(url, headers=headers)
  File "/home/fantasai/w3c/bikeshed/bikeshed/requests/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/home/fantasai/w3c/bikeshed/bikeshed/requests/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fantasai/w3c/bikeshed/bikeshed/requests/requests/sessions.py", line 477, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/fantasai/w3c/bikeshed/bikeshed/requests/requests/sessions.py", line 587, in send
    r = adapter.send(request, **kwargs)
  File "/home/fantasai/w3c/bikeshed/bikeshed/requests/requests/adapters.py", line 481, in send
    raise ConnectionError(e, request=request)
bikeshed.requests.requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/w3c/csswg-drafts/issues/383 (Caused by NewConnectionError('<bikeshed.requests.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f07a0806f90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
```

**Comment by fantasai** [comment]
```
Fetching issue   1/1: w3c/csswg-drafts/383
Traceback (most recent call last):
  File "/home/fantasai/.local/bin/bikeshed", line 11, in <module>
    load_entry_point('Bikeshed', 'console_scripts', 'bikeshed')()
  File "/home/fantasai/w3c/bikeshed/bikeshed/__init__.py", line 214, in main
    doc.preprocess()
  File "/home/fantasai/w3c/bikeshed/bikeshed/__init__.py", line 595, in preprocess
    inlineRemoteIssues(self)
  File "/home/fantasai/w3c/bikeshed/bikeshed/__init__.py", line 2321, in inlineRemoteIssues
    except bikeshed.requests.requests.exceptions.ConnectionError:
NameError: global name 'bikeshed' is not defined
```

**Comment by fantasai** [comment]
```
Fetching issue   1/1: w3c/csswg-drafts/383
Traceback (most recent call last):
  File "/home/fantasai/.local/bin/bikeshed", line 11, in <module>
    load_entry_point('Bikeshed', 'console_scripts', 'bikeshed')()
  File "/home/fantasai/w3c/bikeshed/bikeshed/__init__.py", line 214, in main
    doc.preprocess()
  File "/home/fantasai/w3c/bikeshed/bikeshed/__init__.py", line 595, in preprocess
    inlineRemoteIssues(self)
  File "/home/fantasai/w3c/bikeshed/bikeshed/__init__.py", line 2328, in inlineRemoteIssues
    if res.status_code == 304:
UnboundLocalError: local variable 'res' referenced before assignment
```

**Comment by tabatkins** [comment]
All fixed. ^_^
