### ISSUE TITLE
Crash when building latest version of Service Worker specification

### ISSUE THREAD

**Issue by jugglinmike** [tabatkins/bikeshed#968]
The latest version of the ServiceWorker specification causes the latest verison of Bikeshed to crash with the following error:

    Traceback (most recent call last):
      File "/home/mike/.virtualenvs/wpt/bin/bikeshed", line 11, in <module>
        load_entry_point('Bikeshed', 'console_scripts', 'bikeshed')()
      File "/home/mike/projects/bocoup/google-wpt/bikeshed/bikeshed/__init__.py", line 214, in main
        doc.preprocess()
      File "/home/mike/projects/bocoup/google-wpt/bikeshed/bikeshed/__init__.py", line 598, in preprocess
        processBiblioLinks(self)
      File "/home/mike/projects/bocoup/google-wpt/bikeshed/bikeshed/__init__.py", line 1373, in processBiblioLinks
        linkText = determineLinkText(el)
      File "/home/mike/projects/bocoup/google-wpt/bikeshed/bikeshed/__init__.py", line 1333, in determineLinkText
        elif config.linkTypeIn(linkType, "function") and re.match(r"^[\w-]+\(.*\)$", contents):
      File "/home/mike/projects/bocoup/google-wpt/bikeshed/bikeshed/config.py", line 279, in linkTypeIn
        linkTypes = linkTypeToDfnType[linkTypes]
    KeyError: 'biblio'

- Specification source: https://github.com/w3c/ServiceWorker/blob/93a93ab06ba64dfada14c1543edcc2a679154989/docs/index.bs
- Bikeshed version: 0f4697271bbbaeef35323d2211ff865ee6dd1178

The problem seems to have been introduced in the following commit to Bikeshed: 8e9d9e60e0efbffc4b9de3f687c6eff6bb660698 -- Bikeshed does not crash when run at that commit's parent against the same document.

**Comment by tabatkins** [comment]
Fixed!

**Comment by jugglinmike** [comment]
Verified. Commit: https://github.com/tabatkins/bikeshed/commit/b734e371910e25ac23b774dca3dea5cfc7b7fc0b

Thanks, @tabatkins!
